### ISSUE TITLE
Support for 212.* version

### ISSUE THREAD

**Issue by jak-hammond** [geraldtancl/veracode.plugin#1]
Hi there, I just tried to download and install this plugin, but when I did, I was greeted with the below error;
![image](https://user-images.githubusercontent.com/664193/138907792-2e34da25-1dbc-4489-bab5-144aa0fedddb.png)

Is there any ETA on when this version of Rider might be supported by the plugin?

**Comment by jak-hammond** [comment]
Looking at the manifest for the plugin, I imagine it would be a case of just bumping the version in here; https://github.com/geraldtancl/veracode.plugin/blob/d652ccb2778e4db1fad45170e926c1ccfed1241e/src/main/resources/META-INF/plugin.xml

**Comment by geraldtancl** [comment]
hey Jak, it should be supported by now! Just checking in to see if you still face any issue.

**Comment by jak-hammond** [comment]
This seems to be working now, thanks!
